name: 'Ubuntu 16.04'

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
    - run: |
        eval "$(rbenv init -)"
        rbenv install 2.5.7
        rbenv install 2.6.5
        rbenv install 2.7.0
    